export const TRIP_STATUS = {
  GOING: 'GOING',
  FINISHED: 'FINISHED',
  CANCELLED: 'CANCELLED'
};

export const TRIP_DETAIL_STATUS = {
  WAITING: 'WAITING',
  PICKED_UP: 'PICKED_UP',
  FINISHED: 'FINISHED',
  SKIPPED: 'SKIPPED',
  CANCELLED: 'CANCELLED'
};

export const CONTRACT_STATUS = {
  ACTIVE: 'ACTIVE',
  INACTIVE: 'INACTIVE',
  PENDING: 'PENDING',
  REJECTED: 'REJECTED',
  FUTURE: 'FUTURE',
  FINISHED: 'FINISHED',
  DELETED: 'DELETED',
  EXTENDING: 'EXTENDING',
  TEMP: 'TEMP',
  TEMP_PENDING: 'TEMP_PENDING'
};
