export const SERVICE_OPENING = 'SERVICE_OPENING';
export const SERVICES = 'SERVICES';
export const SERVICE_DETAIL = 'SERVICE_DETAIL';
export const DRIVE_COMPLETION = 'DRIVE_COMPLETION';
export const CAR_UPDATING = 'CAR_UPDATING';
export const FEEDBACK_REVIEW = "FEEDBACK_REVIEW";