export const SERVICE_REQUIREMENT = 'SERVICE_REQUIREMENT';
export const REQUIREMENTS = 'REQUIREMENTS';
export const REQUIREMENT_DETAIL = 'REQUIREMENT_DETAIL';
export const CHOOSE_SERVICE = 'CHOOSE_SERVICE';
export const FEEDBACK = 'FEEDBACK';
export const CONTRACT_EXTENDING = 'CONTRACT_EXTENDING';